intro:
	cd 00-introduction;\
	Rscript -e 'rmarkdown::render("intro.Rmd")'

ids:
	cd 01-taxonomy;\
	Rscript -e 'rmarkdown::render("identifiers.Rmd")'

countries:
	cd 02-biodiversity;\
	Rscript -e 'rmarkdown::render("usecase-countries.Rmd")'

rgbifcleaning:
	cd 02-biodiversity;\
	Rscript -e 'rmarkdown::render("rgbif_cleaning.Rmd")'

datacleaning:
	cd 02-biodiversity;\
	Rscript -e 'rmarkdown::render("data_cleaning.Rmd")'

mapping:
	cd 02-biodiversity;\
	Rscript -e 'rmarkdown::render("mapping.Rmd")'
